import Head from 'next/head'
import { NextPage } from 'next';
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/Banner'
import type { Profile } from '@/types'
import PersonalitySummary from '@/components/PersonalitySummary';
import Bio from '@/components/Bio';

type Props = {
  profile: Profile[];
}

const Home: NextPage<Props> = ({ profile }) => {
  console.log(profile, 'hello from app');
  return (
    <>
      <Head>
        <title>Dimensional</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="flex flex-row justify-around">
          <div className="flex flex-col w-2/5 mx-16">
            <Bio profile={profile}/>
          </div>
          <div className="flex flex-col w-3/5">
            <Banner profile={profile}/> 
            <PersonalitySummary profile={profile}/>
          </div>
        </div>
      </main>
    </>
  )
}

Home.getInitialProps = async (ctx: any) => {
  const res = await fetch('https://us-central1-dimensional-test-9f5ab.cloudfunctions.net/app/profiles')
  const json = await res.json()
  return { profile: json };
}

export default Home;
